[package]
name = "google-cloud-googleapis"
version = "0.1.0"
authors = ["yoshidan <naohiro.y@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tonic = "0.5.2"
prost = "0.8.0"
prost-types = "0.8.0"

[build-dependencies]
tonic-build = "0.5.2"